### ISSUE TITLE
Servicios api Cuba

### ISSUE THREAD

**Issue by Victor1995-2** [kenriortega/servicios-api-cuba#2]

**Comment by TecnoNew365** [comment]
Endpoint https://www.tusitio.cubava.cu/wp-json/wp/v2/pages representa un listado de formato json con todas las paginas del sitio y sus datos asociados
Endpoint https://www.tusitio.cubava.cu/wp-json/wp/v2/posts representa un listado de formato json con todas las entradas o publicaciones del sitio y sus datos asociados
Endpoint https://www.tusitio.cubava.cu/wp-json/wp/v2/comments representa un listado de formato json con todos los comentarios del sitio y sus datos asociados
