### ISSUE TITLE
Cubava ofrece servicio de REST API v2 de Wordpress

### ISSUE THREAD

**Issue by UnCubanoDev** [kenriortega/servicios-api-cuba#3]
Endpoint https://www.{nombre-del-sitio}.cubava.cu/wp-json/wp/v2/pages representa un listado de formato json con todas las paginas del sitio y sus datos asociados
Endpoint https://www.{nombre-del-sitio}.cubava.cu/wp-json/wp/v2/posts representa un listado de formato json con todas las entradas o publicaciones del sitio y sus datos asociados
Endpoint https://www.{nombre-del-sitio}.cubava.cu/wp-json/wp/v2/comments representa un listado de formato json con todos los comentarios del sitio y sus datos asociados

**Comment by kenriortega** [comment]
Estuve tratando de entrar a los servicios que compartes y no existes podrias actualizarlos thx de antemano

**Comment by UnCubanoDev** [comment]
> Estuve tratando de entrar a los servicios que compartes y no existes podrias actualizarlos thx de antemano

En donde dice {nombre-del-sitio} lo puedes sutituir por el nombre de cualquier blog hospedado en cubava!!!! ya sea jorgen, notideporte, itecnogeek, etc...

**Comment by kenriortega** [comment]
Genial voy a tomar de referencia la forma de poner los datos genericos, {dato-generico}
